# 📋 Task 1 : Understanding Dataset & Data Types

## 🎯 Objective
Understand the structure, data types, and ML readiness of the Titanic dataset.

## **Importing Required modules - numpy and pandas**

In [ ]:
import numpy as np
import pandas as pd

## 1. **Loaded the Dataset**
- Used Pandas to load `train.csv`
- Displayed first and last few records using `head()` and `tail()`

In [ ]:
train_dataset = pd.read_csv('student_performance.csv')

In [ ]:
train_dataset.head() # if we send a value inside, it will return the no of rows from first to required.

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,1,3,16,13,0,2,0,0,0,0,3.158425,1
1,1002,18,1,2,0,17,28,0,2,1,1,1,0,2.794655,2
2,1003,15,1,0,1,13,18,1,4,0,0,0,1,3.774847,0
3,1004,17,1,0,3,6,4,0,3,1,0,0,0,3.040574,1
4,1005,17,0,1,2,6,20,0,4,0,0,0,0,3.382310,1

In [ ]:
train_dataset.tail() # if we send a value inside, it will return the no of rows from last to required

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
4995,5996,15,0,3,2,12,22,0,2,0,1,1,0,4.000000,0
4996,5997,16,0,1,2,1,2,0,2,0,1,0,0,2.533415,2
4997,5998,17,1,1,3,18,18,1,0,1,0,0,1,4.000000,0
4998,5999,16,0,2,2,15,0,0,2,1,1,1,0,4.000000,0
4999,6000,18,1,2,4,4,23,0,0,1,0,0,1,2.000000,3

## **2. Identified Data Types**
###Student Performance Dataset – Columns

**StudentID** – Numerical – Unique ID for each student

**Age** – Numerical (Discrete) – Age of the student in years

**Gender** – Categorical (Binary) – 0 = Female, 1 = Male

**Ethnicity** – Categorical (Nominal) – Encoded ethnicity group of the student

**ParentalEducation** – Categorical (Ordinal) – Education level of parents (ordered from low to high)

**StudyTimeWeekly** – Numerical (Continuous) – Weekly study time in hours

**Absences** – Numerical (Discrete) – Number of days the student was absent

**Tutoring** – Categorical (Binary) – 0 = No, 1 = Yes

**ParentalSupport** – Categorical (Ordinal) – Level of parental support (low → high)

**Extracurricular** – Categorical (Binary) – 0 = No, 1 = Yes

**Sports** – Categorical (Binary) – 0 = No, 1 = Yes

**Music** – Categorical (Binary) – 0 = No, 1 = Yes

**Volunteering** – Categorical (Binary) – 0 = No, 1 = Yes

**GPA** – Numerical (Continuous) – Grade Point Average of the student

**GradeClass** – Categorical (Ordinal) – Final grade category of the student (TARGET VARIABLE)

In [ ]:
train_dataset

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,1,3,16,13,0,2,0,0,0,0,3.158425,1
1,1002,18,1,2,0,17,28,0,2,1,1,1,0,2.794655,2
2,1003,15,1,0,1,13,18,1,4,0,0,0,1,3.774847,0
3,1004,17,1,0,3,6,4,0,3,1,0,0,0,3.040574,1
4,1005,17,0,1,2,6,20,0,4,0,0,0,0,3.382310,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,5996,15,0,3,2,12,22,0,2,0,1,1,0,4.000000,0
4996,5997,16,0,1,2,1,2,0,2,0,1,0,0,2.533415,2
4997,5998,17,1,1,3,18,18,1,0,1,0,0,1,4.000000,0
4998,5999,16,0,2,2,15,0,0,2,1,1,1,0,4.000000,0
4999,6000,18,1,2,4,4,23,0,0,1,0,0,1,2.000000,3

## 3. **Analyzed Dataset**
- Used `df.info()` to check data types and null values
- Used `df.describe()` for statistical summary

In [ ]:
train_dataset.dtypes # can also use this if you want nice format of types

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly        int64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass             int64
dtype: object

In [ ]:
train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          5000 non-null   int64
 1   Age                5000 non-null   int64
 2   Gender             5000 non-null   int64
 3   Ethnicity          5000 non-null   int64
 4   ParentalEducation  5000 non-null   int64
 5   StudyTimeWeekly    5000 non-null   int64
 6   Absences           5000 non-null   int64
 7   Tutoring           5000 non-null   int64
 8   ParentalSupport    5000 non-null   int64
 9   Extracurricular    5000 non-null   int64
 10  Sports             5000 non-null   int64
 11  Music              5000 non-null   int64
 12  Volunteering       5000 non-null   int64
 13  GPA                5000 non-null   float64
 14  GradeClass         5000 non-null   int64
dtypes: float64(1), int64(14)
memory usage: 586.1 KB

In [ ]:
train_dataset.describe() # prints count,mean,standard deviation,min,max,etc..

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,3500.500000,16.485200,0.510200,0.885400,2.099400,10.031800,15.065200,0.312200,2.296600,0.59480,0.406600,0.304000,0.302400,3.285252,1.029600
std,1443.520003,1.127136,0.499946,1.038885,1.229074,6.019438,8.922223,0.463437,1.223817,0.49098,0.491248,0.460029,0.459343,0.610250,1.076548
min,1001.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,2.000000,0.000000
25%,2250.750000,15.000000,0.000000,0.000000,1.000000,5.000000,8.000000,0.000000,2.000000,0.00000,0.000000,0.000000,0.000000,2.810158,0.000000
50%,3500.500000,16.000000,1.000000,0.000000,2.000000,10.000000,15.000000,0.000000,2.000000,1.00000,0.000000,0.000000,0.000000,3.359485,1.000000
75%,4750.250000,18.000000,1.000000,2.000000,3.000000,15.000000,23.000000,1.000000,3.000000,1.00000,1.000000,1.000000,1.000000,3.893944,2.000000
max,6000.000000,18.000000,1.000000,3.000000,4.000000,20.000000,30.000000,1.000000,4.000000,1.00000,1.000000,1.000000,1.000000,4.000000,3.000000

In [ ]:
train_dataset.isnull() # Returns a DataFrame of the same shape with True where values are missing and False otherwise.

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
train_dataset.isnull().sum() # Returns missing values per column.

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [ ]:
train_dataset.notnull().sum() # Returns non-null no of values

StudentID            5000
Age                  5000
Gender               5000
Ethnicity            5000
ParentalEducation    5000
StudyTimeWeekly      5000
Absences             5000
Tutoring             5000
ParentalSupport      5000
Extracurricular      5000
Sports               5000
Music                5000
Volunteering         5000
GPA                  5000
GradeClass           5000
dtype: int64

## 4. **Categorical Data Distribution Analysis**
- Analyzed unique values in all categorical columns.
- Identified the number of distinct categories in each feature.
- Observed binary, nominal, and ordinal categories such as Gender, Tutoring, and ParentalEducation.

In [ ]:
train_dataset['Gender'].unique() # Checks Unique Values in Categorical Columns

array([1, 0])

In [ ]:
train_dataset['Ethnicity'].unique()

array([1, 2, 0, 3])

In [ ]:
train_dataset['ParentalEducation'].unique()

array([3, 0, 1, 2, 4])

In [ ]:
train_dataset['Tutoring'].unique()

array([0, 1])

In [ ]:
train_dataset['ParentalSupport'].unique()

array([2, 4, 3, 1, 0])

In [ ]:
train_dataset['Extracurricular'].unique()

array([0, 1])

In [ ]:
train_dataset['Sports'].unique()

array([0, 1])

In [ ]:
train_dataset['Music'].unique()

array([0, 1])

In [ ]:
train_dataset['Volunteering'].unique()

array([0, 1])

In [ ]:
train_dataset['GradeClass'].unique()

array([1, 2, 0, 3])

In [ ]:
categorical_cols = [
    'Gender', 'Ethnicity', 'ParentalEducation', 'Tutoring',
    'ParentalSupport', 'Extracurricular', 'Sports',
    'Music', 'Volunteering', 'GradeClass'
]

for col in categorical_cols:
    print(f"\nColumn: {col}")
    print("Unique values:", train_dataset[col].nunique())
    print(train_dataset[col].value_counts())
    print('-------------------------------------------------------------')

Column: Gender
Unique values: 2
Gender
1    2551
0    2449
Name: count, dtype: int64
-------------------------------------------------------------

Column: Ethnicity
Unique values: 4
Ethnicity
0    2533
2     992
1     991
3     484
Name: count, dtype: int64
-------------------------------------------------------------

Column: ParentalEducation
Unique values: 5
ParentalEducation
2    1272
3    1232
1    1205
4     763
0     528
Name: count, dtype: int64
-------------------------------------------------------------

Column: Tutoring
Unique values: 2
Tutoring
0    3439
1    1561
Name: count, dtype: int64
-------------------------------------------------------------

Column: ParentalSupport
Unique values: 5
ParentalSupport
2    1567
3    1227
4     990
1     708
0     508
Name: count, dtype: int64
-------------------------------------------------------------

Column: Extracurricular
Unique values: 2
Extracurricular
1    2974
0    2026
Name: count, dtype: int64
-------------------------------------------------------------

Column: Sports
Unique values: 2
Sports
0    2967
1    2033
Name: count, dtype: int64
-------------------------------------------------------------

Column: Music
Unique values: 2
Music
0    3480
1    1520
Name: count, dtype: int64
-------------------------------------------------------------

Column: Volunteering
Unique values: 2
Volunteering
0    3488
1    1512
Name: count, dtype: int64
-------------------------------------------------------------

Column: GradeClass
Unique values: 4
GradeClass
0    2175
1    1152
2    1023
3     650
Name: count, dtype: int64
-------------------------------------------------------------

## **5. Identifying Target Variable and Input Features**

- The target variable is the column that the model aims to predict.

- In the Student Performance dataset, GradeClass is the target variable.

- It represents an ordinal multi-class classification problem (performance categories ordered from low to high).

- Input features are the columns used to make predictions.

- Features such as Age, Gender, Ethnicity, ParentalEducation, StudyTimeWeekly, Absences, Tutoring, ParentalSupport, Extracurricular, Sports, Music, Volunteering, and GPA are suitable for modeling.

- Identifier-like columns such as StudentID are not useful for prediction and should be removed before training.

In [ ]:
#If we want to predict the survival based on the dataset we can deop 'PassengerId' and 'ticket'
train_dataset_filter = train_dataset.drop(columns=['StudentID']) # Once run,we cannot take back the data if put into same variable

In [ ]:
input_features = train_dataset_filter.drop(columns='GradeClass')
input_features

,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA
0,17,1,1,3,16,13,0,2,0,0,0,0,3.158425
1,18,1,2,0,17,28,0,2,1,1,1,0,2.794655
2,15,1,0,1,13,18,1,4,0,0,0,1,3.774847
3,17,1,0,3,6,4,0,3,1,0,0,0,3.040574
4,17,0,1,2,6,20,0,4,0,0,0,0,3.382310
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,15,0,3,2,12,22,0,2,0,1,1,0,4.000000
4996,16,0,1,2,1,2,0,2,0,1,0,0,2.533415
4997,17,1,1,3,18,18,1,0,1,0,0,1,4.000000
4998,16,0,2,2,15,0,0,2,1,1,1,0,4.000000
4999,18,1,2,4,4,23,0,0,1,0,0,1,2.000000

In [ ]:
target_features = train_dataset_filter['GradeClass']
target_features

0       1
1       2
2       0
3       1
4       1
       ..
4995    0
4996    2
4997    0
4998    0
4999    3
Name: GradeClass, Length: 5000, dtype: int64

## 6. **Dataset Size and Machine Learning Suitability**

- The Student Performance dataset contains 5,000 rows and 15 columns.

- This is considered a moderate-sized dataset, which is suitable for most machine learning models.

- The dataset has a clearly defined target variable (GradeClass) and meaningful input features.

- It represents a real-world educational performance prediction problem, making it suitable for classification models.

- With sufficient data size, the risk of overfitting is lower compared to very small datasets, but proper validation is still necessary.

In [ ]:
train_dataset.shape # Prints the No. of rows and No. of columns
# In order to obtain more accuracy we need to get larger datasets

(5000, 15)

## 7. **Data Quality Observations**

- No missing values are present in any of the columns; the dataset is complete.

- All features such as Age, Gender, GPA, StudyTimeWeekly, and Absences contain valid entries.

- The target variable (GradeClass) shows class imbalance, with some grade categories having more samples than others.

- The column StudentID behaves like an identifier and does not contribute directly to prediction.

- Although the dataset is clean, class imbalance and feature relevance must be handled through preprocessing before training machine learning models.

In [ ]:
train_dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
(train_dataset.isnull().sum() / len(train_dataset)) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [39]:
train_dataset['GradeClass'].value_counts() # Checks class imbalance

GradeClass
0    2175
1    1152
2    1023
3     650
Name: count, dtype: int64